### ISSUE TITLE
security.existingSecret doesn't work properly

### ISSUE THREAD

**Issue by hershellayton95** [captnbp/opensearch-helm#1]
Hi,

I've run into an issue while trying to use `security.existingSecret` to provide an external secret to the cluster.
Unfortunately, it doesn't work as expected.

For instance, if I set `security.existingSecret: xyz`, the pods still require a secret named <release name>-<chart name>.

This appears to be caused by a missing check for security.existingSecret in StatefulSets and Jobs. 

example in cluster_manager statefulset.yaml
```yaml
Copia codice
- name: MONITORING_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ template "common.names.fullname" . }}
      key: monitoring-password
```
